### ISSUE TITLE
你好，请问提供生成dataset_info文件夹里的pkl文件的代码吗

### ISSUE THREAD

**Issue by breeze623** [AntonotnaWang/NaviAirway#2]
由于数据集不一样我们在使用你的模型的过程中需要重新编写pkl文件，但是在你的pkl文件中发现存在airway_pixel_num等参数，我们不清楚是怎么得到的，希望你可以提供pkl文件的生成代码以供参考，谢谢

**Comment by AntonotnaWang** [comment]
sorry，我没写清楚，pkl文件的生成用Get_dataset_info.ipynb
